steps:
# Step 1: Build the container image using the Dockerfile.
# Tag it with both the unique commit ID and the 'latest' tag for convenience.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/simple-time-api/api-image:$COMMIT_SHA',
    '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/simple-time-api/api-image:latest',
    '.'
  ]

# Step 2: Push the image with the specific commit SHA tag to Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/simple-time-api/api-image:$COMMIT_SHA']

# Step 3: Push the image with the 'latest' tag to Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/simple-time-api/api-image:latest']

# Step 4: Deploy the newly pushed image to our Cloud Run service.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'simple-time-api-service'  # This is the name of our Cloud Run service
  - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/simple-time-api/api-image:latest'
  - '--region=us-central1'
  - '--platform=managed'
  - '--allow-unauthenticated'

# We set the logging option as a best practice for custom service accounts.
options:
  logging: CLOUD_LOGGING_ONLY
